[package]
name = "lancelot"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "^0.5.0"
goblin = "0.0.18"
# zydis-c requires `cmake`, so ensure to have that first.
zydis = { git = "https://github.com/zyantific/zydis-rs"}
rayon = "1.0"
matches = "0.1.8"