[workspace]

members = [
    "core",
    "flirt",
    "pyflirt",
    "pylancelot",
    "jslancelot",
    "bin",
]

[profile.release]
# temporarily disabled due to: https://github.com/zyantific/zydis-rs/issues/29
lto = "fat"
codegen-units = 1
