[package]
name = "lancelot"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "^0.5.0"
goblin = "0.0.22"
# zydis==0.0.3 requires rust-bindgen, which requires clang 3.9
zydis = "0.0.3"
matches = "0.1.8"
byteorder = "1.2.7"
num = "0.2"
num-traits = "0.2"
strum = "0.15"
strum_macros = "0.15"
failure = "0.1.5"
bitflags = "1.0.4"
# upgrade to 0.4.5 once available
# see: https://github.com/pyros2097/rust-embed/pull/67
rust-embed = { git="https://github.com/pyros2097/rust-embed", rev="7ea8ef21b14951ca3c7f60f9b6d7cc223923c5ba", features=["debug-embed", "interpolate-folder-path"] }

xml-rs = "0.8"
better-panic = "0.1.1"
md5 = "0.6.1"
regex = "1.1.7"

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
test = []
