[package]
name = "lancelot"
description = "binary analysis framework for x32/x64 PE files"
license = "Apache-2.0"
version = "0.2.1"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "https://github.com/williballenthin/lancelot", branch = "master" }

[dependencies]
log = "0.4"
goblin = "0.2"
zydis = "3"
byteorder = "1"
bitflags = "1"
lazy_static = "1"
fern = "0.6"
chrono = "0.4"
anyhow = "1"
thiserror = "1"
regex = "1"
smallvec = "1"
widestring = "0.4"

#lancelot-flirt = { path = "../flirt" , optional = true}
lancelot-flirt = { version = "0.2" , optional = true}

[features]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
test = []