[package]
name = "pylancelot"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[lib]
name = "pylancelot"
crate-type = ["cdylib"]

[dependencies]
lancelot = { path = "../core" }
pyo3 = { version = "0.11"}

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

[package.metadata.maturin]
classifier = [
  "Programming Language :: Rust",
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Topic :: Security",
  "Topic :: Software Development :: Disassemblers",
]
