on: [push, pull_request]

name: CI

jobs:
  test:
    name: test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: test core
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p lancelot
      - name: test flirt
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p lancelot-flirt
      - name: test pylancelot
        working-directory: ./pylancelot/
        run: |
          sudo apt-get install -y build-essential gcc cmake python3.8 python3.8-dev virtualenv
          mkdir /tmp/vdir
          virtualenv -p python3.8 /tmp/vdir
          source /tmp/vdir/bin/activate
          pip install -U pip setuptools maturin pytest pefile
          maturin develop
          pytest
      - name: test pyflirt
        working-directory: ./pyflirt/
        run: |
          sudo apt-get install -y build-essential gcc cmake python3.8 python3.8-dev virtualenv
          mkdir /tmp/vdir
          virtualenv -p python3.8 /tmp/vdir
          source /tmp/vdir/bin/activate
          pip install -U pip setuptools maturin pytest
          maturin develop
          pytest