on:
  release:
    types: [created, edited]

name: publish cargo

jobs:
  crate:
   name: publish to crates.io
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - uses: actions-rs/toolchain@v1
       with:
         profile: minimal
         toolchain: stable
         override: true

     - name: login
       run: cargo login ${CARGO_TOKEN}
       env:
         CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}

     - name: publish flirt
       run: |
         cd flirt
         cargo publish
         cd ..

     - name: publish core
       run: |
         sleep 60  # give a moment for crates.io to propagate
         cd core
         cargo publish
         cd ..

     - name: publish bin
       run: |
         sleep 60  # give a moment for crates.io to propagate
         cd bin
         cargo publish
         cd ..
